#pragma once
#ifndef __TAG_HEADER_H__
#define __TAG_HEADER_H__

#define PI 3.141592

#define TAG_PLAYER 1
#define TAG_ENEMY 10
#define TAG_BULLET_PLAYER 101
#define TAG_BULLET_ENEMY 1010
#define TAG_BASIC_MAP 10000
#define TAG_ROCK 101010

#define TEXTURE_CODE_PLAYER 1
#define TEXTURE_CODE_ENEMY 2
#define TEXTURE_CODE_BASIC_MAP 3
#define TEXTURE_CODE_COLOR_RED 4
#define TEXTURE_CODE_COLOR_GREEN 5
#define TEXTURE_CODE_COLOR_BLUE 6
#define TEXTURE_CODE_HELLY 7
#define TEXTURE_CODE_BULLET 1

#define TYPE_ATTACK 0
#define TYPE_DEFENSE 1
#define TYPE_MIX 2


#endif // !__TAG_HEADER_H__
